- name: create a user
  hosts: user
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable default nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
    
  - name: create a robosop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: make a directory
    ansible.builtin.file:
      path: /app 
      state: directory

  - name: download the webiste
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip
    
  - name: extract user code
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app 
      remote_src: yes
  
  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copy user service to system die
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: systemctl deamon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable user
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes
  
